# Modeling

**Approach:** Logistic regression and XGBoost on matchup feature differences; Elo-style rating model for a third probability stream. **Evaluation:** Log loss. **Validation:** Time-based CV by season (train on past seasons, validate on one season)—never use a random split.

In [48]:
import sys
sys.path.insert(0, '..')
import importlib
import src.features
import src.data_loading
import src.splits
import src.train_logreg
import src.train_xgb
import src.matchup_builder
import src.predict_2026
import src.named_matchups
import pandas as pd

importlib.reload(src.features)
importlib.reload(src.data_loading)
importlib.reload(src.splits)
importlib.reload(src.train_logreg)
importlib.reload(src.train_xgb)
importlib.reload(src.matchup_builder)
importlib.reload(src.predict_2026)
importlib.reload(src.named_matchups)

In [49]:
import sys
sys.path.insert(0, '..')
from src import validation, train_logreg, train_xgb

# Stubs: get_time_splits(seasons, n_splits), evaluate_cv(model, X, y, splits)
try:
    validation.get_time_splits([1985, 1986, 1987], n_splits=2)
except NotImplementedError:
    print("validation.get_time_splits: implement time-based folds.")

# Same time-based train/val split via `src.splits.split_matchup_train_val` (Season <= 2018 vs later).
train_logreg.train_logreg(None, None)
train_xgb.train_xgb()

validation.get_time_splits: implement time-based folds.
Baseline (6 feats) log loss: 0.5763305764083805
DROP  - efg_pct_diff           -> 0.5763711959019736
DROP  - tov_pct_diff           -> 0.5764323426168473
KEEP  + orb_pct_diff           -> 0.5761538002825893
KEEP  + ftr_diff               -> 0.5755634842761634
DROP  - last10_net_eff_diff    -> 0.5817279093161941
Final (8 feats) log loss: 0.5755634842761634
Final features: ['seed_diff', 'avg_margin_diff', 'off_eff_diff', 'def_eff_diff', 'net_eff_diff', 'win_pct_diff', 'orb_pct_diff', 'ftr_diff']
      target      pred  seed_diff  avg_margin_diff  off_eff_diff  \
2096       1  0.669373        0.0         8.512500     11.111882
2097       0  0.330627        0.0        -8.512500    -11.111882
2098       1  0.549169        0.0         0.136852      5.162797
2099       0  0.450831        0.0        -0.136852     -5.162797
2100       1  0.504676        0.0         2.022727      0.435941
2101       0  0.495324        0.0        -2.022727     -0.435941
2102       1  0.417377        0.0        -1.284946      7.690525
2103       0  0.582623        0.0         1.284946     -7.690525
2104       1  0.880302      -13.0         4.475444      5.682317
2105       0  0.119698       13.0        -4.475444     -5.682317
2106       1  0.684417       -7.0        -2.549632      0.042999
2107       0  0.315583        7.0         2.549632     -0.042999
2108       1  0.511228        1.0         0.438447      3.723336
2109       0  0.488772       -1.0        -0.438447     -3.723336
2110       1  0.574223       -5.0        -5.918750     -9.084910
2111       0  0.425777        5.0         5.918750      9.084910
2112       1  0.932694      -13.0        12.112299     14.019518
2113       0  0.067306       13.0       -12.112299    -14.019518
2114       1  0.972057      -15.0        21.529814     15.546598
2115       0  0.027943       15.0       -21.529814    -15.546598
2116       1  0.346350        3.0        -9.382353     -9.583202
2117       0  0.653650       -3.0         9.382353      9.583202
2118       1  0.725272       -9.0        -1.768382     -3.297102
2119       0  0.274728        9.0         1.768382      3.297102
2120       1  0.763243       -9.0        -0.524064     -7.400764
2121       0  0.236757        9.0         0.524064      7.400764
2122       1  0.274049        3.0        -5.109626     -3.800132
2123       0  0.725951       -3.0         5.109626      3.800132
2124       1  0.807766      -11.0         1.165179      2.415983
2125       0  0.192234       11.0        -1.165179     -2.415983
2126       1  0.369595        7.0         4.570533      6.021640
2127       0  0.630405       -7.0        -4.570533     -6.021640
2128       1  0.898314      -13.0         4.479779     -3.503316
2129       0  0.101686       13.0        -4.479779      3.503316
2130       1  0.857478      -11.0         4.051471     12.658037
2131       0  0.142522       11.0        -4.051471    -12.658037
2132       1  0.790364       -3.0        11.212121     13.404842
2133       0  0.209636        3.0       -11.212121    -13.404842
2134       1  0.575077       -5.0        -1.163102     -0.332616
2135       0  0.424923        5.0         1.163102      0.332616
2136       1  0.803796       -5.0         9.068182      6.574026
2137       0  0.196204        5.0        -9.068182     -6.574026
2138       1  0.286287        3.0        -4.833333      0.768995
2139       0  0.713713       -3.0         4.833333     -0.768995
2140       1  0.886983      -13.0         6.757576      5.647119
2141       0  0.113017       13.0        -6.757576     -5.647119
2142       1  0.964895      -15.0        17.392789      4.931933
2143       0  0.035105       15.0       -17.392789     -4.931933
2144       1  0.968586      -15.0        14.426411      8.482976
2145       0  0.031414       15.0       -14.426411     -8.482976
2146       1  0.927294      -11.0        11.632353      5.504559
2147       0  0.072706       11.0       -11.632353     -5.504559
2148       1  0.944570      -15.0        11.902462      4.516000
2149       0  0.055430       15.0       -11.902462     -4.516000
2150       1  0.239718        5.0        -5.693405     -9.558509
2151       0  0.760282       -5.0         5.693405      9.558509
2152       1  0.276131        9.0         2.277184      6.674647
2153       0  0.723869       -9.0        -2.277184     -6.674647
2154       1  0.344077        7.0         2.691105     -0.442895
2155       0  0.655923       -7.0        -2.691105      0.442895

      def_eff_diff  net_eff_diff  win_pct_diff  orb_pct_diff  ftr_diff
2096     -0.490792     11.602674      0.114583     -0.005120 -0.050851
2097      0.490792    -11.602674     -0.114583      0.005120  0.050851
2098      4.880874      0.281924     -0.055718     -0.002726 -0.089353
2099     -4.880874     -0.281924      0.055718      0.002726  0.089353
2100     -2.709515      3.145456      0.051136      0.111601  0.139932
2101      2.709515     -3.145456     -0.051136     -0.111601 -0.139932
2102      9.307638     -1.617113      0.016129     -0.139346  0.001173
2103     -9.307638      1.617113     -0.016129      0.139346 -0.001173
2104     -1.066570      6.748888      0.025078      0.091025  0.086504
2105      1.066570     -6.748888     -0.025078     -0.091025 -0.086504
2106      4.025232     -3.982233     -0.139706     -0.046629 -0.030915
2107     -4.025232      3.982233      0.139706      0.046629  0.030915
2108      3.406767      0.316569     -0.012311      0.082642 -0.041391
2109     -3.406767     -0.316569      0.012311     -0.082642  0.041391
2110     -1.231172     -7.853738     -0.145833      0.081824  0.045752
2111      1.231172      7.853738      0.145833     -0.081824 -0.045752
2112     -3.635711     17.655229      0.247772      0.072127 -0.012973
2113      3.635711    -17.655229     -0.247772     -0.072127  0.012973
2114    -13.875402     29.422000      0.328446      0.007845 -0.001628
2115     13.875402    -29.422000     -0.328446     -0.007845  0.001628
2116      2.866115    -12.449317     -0.319964      0.050454 -0.100293
2117     -2.866115     12.449317      0.319964     -0.050454  0.100293
2118      1.028532     -4.325635     -0.018382      0.058322  0.006535
2119     -1.028532      4.325635      0.018382     -0.058322 -0.006535
2120     -5.932824     -1.467941      0.038324      0.070356 -0.011978
2121      5.932824      1.467941     -0.038324     -0.070356  0.011978
2122      3.902492     -7.702624      0.011586      0.019385  0.053579
2123     -3.902492      7.702624     -0.011586     -0.019385 -0.053579
2124      0.618426      1.797557      0.062500      0.111483  0.070378
2125     -0.618426     -1.797557     -0.062500     -0.111483 -0.070378
2126     -0.693032      6.714672      0.134796      0.038578 -0.021359
2127      0.693032     -6.714672     -0.134796     -0.038578  0.021359
2128    -11.088934      7.585618      0.073529     -0.030380 -0.048012
2129     11.088934     -7.585618     -0.073529      0.030380  0.048012
2130      6.718282      5.939755     -0.045956      0.025739  0.002100
2131     -6.718282     -5.939755      0.045956     -0.025739 -0.002100
2132     -2.983623     16.388465      0.260606      0.033327 -0.075706
2133      2.983623    -16.388465     -0.260606     -0.033327  0.075706
2134      2.209340     -2.541955      0.068627     -0.002618  0.057568
2135     -2.209340      2.541955     -0.068627      0.002618 -0.057568
2136     -5.350121     11.924147      0.221591     -0.008694 -0.113329
2137      5.350121    -11.924147     -0.221591      0.008694  0.113329
2138      8.585236     -7.816241     -0.156863     -0.079978  0.039631
2139     -8.585236      7.816241      0.156863      0.079978 -0.039631
2140     -3.809899      9.457018      0.151515      0.015135  0.046072
2141      3.809899     -9.457018     -0.151515     -0.015135 -0.046072
2142    -18.334649     23.266582      0.336812      0.159887  0.018795
2143     18.334649    -23.266582     -0.336812     -0.159887 -0.018795
2144    -15.279377     23.762353      0.261089      0.071867 -0.088644
2145     15.279377    -23.762353     -0.261089     -0.071867  0.088644
2146    -11.644481     17.149040      0.193015      0.120513 -0.036974
2147     11.644481    -17.149040     -0.193015     -0.120513  0.036974
2148     -9.668083     14.184083      0.286932      0.088222 -0.064958
2149      9.668083    -14.184083     -0.286932     -0.088222  0.064958
2150     -0.702474     -8.856035     -0.100713     -0.007662  0.040914
2151      0.702474      8.856035      0.100713      0.007662 -0.040914
2152      2.962120      3.712527      0.095365      0.050683 -0.016644
2153     -2.962120     -3.712527     -0.095365     -0.050683  0.016644
2154     -5.674484      5.231589      0.109482     -0.086858 -0.058269
2155      5.674484     -5.231589     -0.109482      0.086858  0.058269
           feature  coefficient
0     orb_pct_diff     1.028587
1     net_eff_diff     0.033172
2  avg_margin_diff     0.022910
3     off_eff_diff     0.012947
4     def_eff_diff    -0.020225
5        seed_diff    -0.127956
6     win_pct_diff    -1.011673
7         ftr_diff    -1.825745
XGBoost Log Loss: 0.5911528188999162
                feature  importance
0             seed_diff    0.298428
1       avg_margin_diff    0.135888
2          net_eff_diff    0.119619
3              ftr_diff    0.066857
4   last10_net_eff_diff    0.061311
5          orb_pct_diff    0.055179
6          efg_pct_diff    0.054465
7          tov_pct_diff    0.053421
8          def_eff_diff    0.052564
9          off_eff_diff    0.051618
10         win_pct_diff    0.050652

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

Testing building matchup data

In [50]:
from src.matchup_builder import build_matchup_data
from src.data_loading import load_team_names

matchups = build_matchup_data()
matchups.head()

print(matchups.isna().sum().sort_values(ascending=False))

team_names = load_team_names()
df_team_names = pd.DataFrame(team_names)
df_team_names.rename(columns={"TeamID": "TeamA", "TeamName": "TeamA_Name"}, inplace=True)
#df_team_names.rename(columns={"TeamID": "TeamB", "TeamName": "TeamB_Name"}, inplace=True)
#matchups = matchups.merge(df_team_names, on="TeamA", how="left")
df_team_names.rename(columns={"TeamA": "TeamB", "TeamA_Name": "TeamB_Name"}, inplace=True)
#matchups = matchups.merge(df_team_names, on="TeamB", how="left")

# print(matchups.head())
# print(matchups.shape)
# print(matchups["target"].value_counts())
# print(matchups.isna().sum().sort_values(ascending=False).head(10))

matchups = matchups.copy()
matchups["TeamLow"] = matchups[["TeamA", "TeamB"]].min(axis=1)
matchups["TeamHigh"] = matchups[["TeamA", "TeamB"]].max(axis=1)

# For each (Season, unordered team pair), show TeamA winner (target=1) before TeamA loser (target=0)
matchups = matchups.sort_values(
    ["Season", "DayNum", "TeamLow", "TeamHigh", "target", "TeamA", "TeamB"],
    ascending=[True, True, True, True, False, True, True],
).reset_index(drop=True)

matchups = matchups.drop(columns=["TeamLow", "TeamHigh"])
matchups.head(60)

Season                   0
efg_pct_diff             0
lastx_net_eff_diff       0
lastx_def_eff_diff       0
lastx_off_eff_diff       0
lastx_avg_margin_diff    0
lastx_win_pct_diff       0
ftr_diff                 0
orb_pct_diff             0
tov_pct_diff             0
net_eff_diff             0
DayNum                   0
def_eff_diff             0
off_eff_diff             0
avg_margin_diff          0
win_pct_diff             0
seed_diff                0
target                   0
TeamB                    0
TeamA                    0
last10_net_eff_diff      0
dtype: int64

,Season,DayNum,TeamA,TeamB,target,seed_diff,win_pct_diff,avg_margin_diff,off_eff_diff,def_eff_diff,...,efg_pct_diff,tov_pct_diff,orb_pct_diff,ftr_diff,lastx_win_pct_diff,lastx_avg_margin_diff,lastx_off_eff_diff,lastx_def_eff_diff,lastx_net_eff_diff,last10_net_eff_diff
0,2003,134,1421,1411,1,0.0,-0.151724,-9.208046,-1.053720,10.967252,...,-0.013235,0.014303,-0.012949,-0.152277,0.0,-0.3,6.427775,6.807102,-0.379327,-0.379327
1,2003,134,1411,1421,0,0.0,0.151724,9.208046,1.053720,-10.967252,...,0.013235,-0.014303,0.012949,0.152277,0.0,0.3,-6.427775,-6.807102,0.379327,0.379327
2,2003,136,1112,1436,1,-15.0,0.237685,10.309113,7.932821,-3.994784,...,0.022900,-0.022838,0.014010,0.031691,0.1,5.3,4.134648,-1.268476,5.403124,5.403124
3,2003,136,1436,1112,0,15.0,-0.237685,-10.309113,-7.932821,3.994784,...,-0.022900,0.022838,-0.014010,-0.031691,-0.1,-5.3,-4.134648,1.268476,-5.403124,-5.403124
4,2003,136,1113,1272,1,3.0,-0.172414,-1.896552,3.236790,5.700441,...,0.018997,0.005838,0.031277,0.071937,-0.3,-4.6,7.276878,13.624195,-6.347317,-6.347317
5,2003,136,1272,1113,0,-3.0,0.172414,1.896552,-3.236790,-5.700441,...,-0.018997,-0.005838,-0.031277,-0.071937,0.3,4.6,-7.276878,-13.624195,6.347317,6.347317
6,2003,136,1163,1140,1,-7.0,-0.041935,-0.140860,-1.407896,1.095328,...,-0.008439,0.007967,0.060507,-0.118209,-0.1,-0.1,-3.062419,-0.891669,-2.170749,-2.170749
7,2003,136,1140,1163,0,7.0,0.041935,0.140860,1.407896,-1.095328,...,0.008439,-0.007967,-0.060507,0.118209,0.1,0.1,3.062419,0.891669,2.170749,2.170749
8,2003,136,1141,1166,1,5.0,-0.085684,-8.805643,-4.400316,8.325189,...,0.005381,0.060548,0.019944,0.127689,0.1,4.7,11.920584,5.398172,6.522412,6.522412
9,2003,136,1166,1141,0,-5.0,0.085684,8.805643,4.400316,-8.325189,...,-0.005381,-0.060548,-0.019944,-0.127689,-0.1,-4.7,-11.920584,-5.398172,-6.522412,-6.522412
10,2003,136,1143,1301,1,-1.0,0.124138,0.324138,-2.060230,-2.243981,...,-0.010092,-0.011708,0.013497,-0.039185,0.1,3.3,-1.122762,-6.043509,4.920747,4.920747
11,2003,136,1301,1143,0,1.0,-0.124138,-0.324138,2.060230,2.243981,...,0.010092,0.011708,-0.013497,0.039185,-0.1,-3.3,1.122762,6.043509,-4.920747,-4.920747
12,2003,136,1211,1153,1,1.0,0.134793,3.049539,7.564286,2.790273,...,0.070681,0.048143,0.025607,0.078662,0.3,6.8,11.604053,0.025612,11.578441,11.578441
13,2003,136,1153,1211,0,-1.0,-0.134793,-3.049539,-7.564286,-2.790273,...,-0.070681,-0.048143,-0.025607,-0.078662,-0.3,-6.8,-11.604053,-0.025612,-11.578441,-11.578441
14,2003,136,1181,1161,1,-11.0,0.233333,10.233333,3.973800,-10.260364,...,-0.026919,-0.043527,0.013981,-0.003991,0.3,10.3,2.217529,-13.025452,15.242981,15.242981
15,2003,136,1161,1181,0,11.0,-0.233333,-10.233333,-3.973800,10.260364,...,0.026919,0.043527,-0.013981,0.003991,-0.3,-10.3,-2.217529,13.025452,-15.242981,-15.242981
16,2003,136,1409,1173,1,9.0,-0.117909,1.775306,-6.790709,-8.467052,...,-0.002561,0.000029,-0.079459,-0.082767,0.1,6.0,-8.476011,-16.787433,8.311422,8.311422
17,2003,136,1173,1409,0,-9.0,0.117909,-1.775306,6.790709,8.467052,...,0.002561,-0.000029,0.079459,0.082767,-0.1,-6.0,8.476011,16.787433,-8.311422,-8.311422
18,2003,136,1266,1221,1,-11.0,-0.040640,-0.423645,9.471646,10.766415,...,0.026214,-0.013501,0.036462,0.006754,-0.2,-5.2,1.914486,11.096038,-9.181552,-9.181552
19,2003,136,1221,1266,0,11.0,0.040640,0.423645,-9.471646,-10.766415,...,-0.026214,0.013501,-0.036462,-0.006754,0.2,5.2,-1.914486,-11.096038,9.181552,9.181552
20,2003,136,1228,1443,1,-9.0,0.058065,7.355914,4.934126,-5.411292,...,0.018831,-0.026589,-0.049579,-0.049208,-0.2,1.1,4.168506,2.031991,2.136515,2.136515
21,2003,136,1443,1228,0,9.0,-0.058065,-7.355914,-4.934126,5.411292,...,-0.018831,0.026589,0.049579,0.049208,0.2,-1.1,-4.168506,-2.031991,-2.136515,-2.136515
22,2003,136,1242,1429,1,-13.0,0.033333,9.100000,2.203769,-8.595428,...,0.030458,0.001224,-0.008388,-0.002747,0.1,4.4,-1.447757,-5.698752,4.250994,4.250994
23,2003,136,1429,1242,0,13.0,-0.033333,-9.100000,-2.203769,8.595428,...,-0.030458,-0.001224,0.008388,0.002747,-0.1,-4.4,1.447757,5.698752,-4.250994,-4.250994
24,2003,136,1281,1356,1,-5.0,-0.122581,-1.143011,-4.184839,-2.200083,...,-0.018847,0.016963,0.044142,-0.037005,-0.2,-3.6,-8.785715,-3.093156,-5.692558,-5.692558
25,2003,136,1356,1281,0,5.0,0.122581,1.143011,4.184839,2.200083,...,0.018847,-0.016963,-0.044142,0.037005,0.2,3.6,8.785715,3.093156,5.692558,5.692558
26,2003,136,1323,1454,1,-7.0,-0.056989,1.736559,2.232874,0.117572,...,-0.023154,-0.032220,-0.028943,-0.000126,-0.4,-13.3,-0.212122,18.536213,-18.748335,-18.748335
27,2003,136,1454,1323,0,7.0,0.056989,-1.736559,-2.232874,-0.117572,...,0.023154,0.032220,0.028943,0.000126,0.4,13.3,0.212122,-18.536213,18.748335,18.748335
28,2003,136,1328,1354,1,-15.0,0.133333,9.466667,8.308539,-5.449133,...,0.004149,-0.084914,-0.033787,-0.152281,0.1,2.1,-1.057730,-4.399390,3.341660,3.341660
29,2003,136,1354,1328,0,15.0,-0.133333,-9.466667,-8.308539,5.449133,...,-0.004149,0.084914,0.033787,0.152281,-0.1,-2.1,1.057730,4.399390,-3.341660,-3.341660
30,2003,136,1390,1360,1,-9.0,0.134793,2.183180,2.230151,-0.948173,...,-0.031826,-0.040435,0.041195,-0.136919,-0.1,-5.7,-0.415050,7.415149,-7.830200,-7.830200
31,2003,136,1360,1390,0,9.0,-0.134793,-2.183180,-2.230151,0.948173,...,0.031826,0.040435,-0.041195,0.136919,0.1,5.7,0.415050,-7.415149,7.830200,7.830200
32,2003,136,1458,1451,1,-7.0,-0.103448,5.000000,1.269432,-7.430054,...,0.001801,-0.017980,-0.003181,-0.130037,-0.3,-5.5,-7.643763,-1.600016,-6.043746,-6.043746
33,2003,136,1451,1458,0,7.0,0.103448,-5.000000,-1.269432,7.430054,...,-0.001801,0.017980,0.003181,0.130037,0.3,5.5,7.643763,1.600016,6.043746,6.043746
34,2003,137,1231,1104,1,-3.0,0.017857,-0.754464,3.170672,3.894996,...,0.024938,-0.026354,-0.056736,0.043339,0.2,1.4,3.629372,0.923270,2.706102,2.706102
35,2003,137,1104,1231,0,3.0,-0.017857,0.754464,-3.170672,-3.894996,...,-0.024938,0.026354,0.056736,-0.043339,-0.2,-1.4,-3.629372,-0.923270,-2.706102,-2.706102
36,2003,137,1120,1386,1,3.0,-0.159770,-6.811494,-4.352844,7.129800,...,0.000268,0.038119,0.036089,-0.026897,-0.3,-15.5,-15.266321,8.736643,-24.002964,-24.002964
37,2003,137,1386,1120,0,-3.0,0.159770,6.811494,4.352844,-7.129800,...,-0.000268,-0.038119,-0.036089,0.026897,0.3,15.5,15.266321,-8.736643,24.002964,24.002964
38,2003,137,1257,1122,1,-9.0,0.059259,11.366667,9.651422,-5.662966,...,0.015140,-0.041294,0.033905,-0.059564,-0.3,-2.5,2.693059,6.303903,-3.610844,-3.610844
39,2003,137,1122,1257,0,9.0,-0.059259,-11.366667,-9.651422,5.662966,...,-0.015140,0.041294,-0.033905,0.059564,0.3,2.5,-2.693059,-6.303903,3.610844,3.610844
40,2003,137,1139,1280,1,7.0,0.127586,-2.344828,8.830849,9.683588,...,0.040778,-0.063870,-0.105875,0.009050,0.2,0.0,7.835007,6.692106,1.142901,1.142901
41,2003,137,1280,1139,0,-7.0,-0.127586,2.344828,-8.830849,-9.683588,...,-0.040778,0.063870,0.105875,-0.009050,-0.2,0.0,-7.835007,-6.692106,-1.142901,-1.142901
42,2003,137,1277,1160,1,-3.0,-0.032258,0.806452,-2.211763,-4.523975,...,0.014636,0.028270,-0.041054,0.046555,0.0,2.1,-3.449001,-7.261681,3.812680,3.812680
43,2003,137,1160,1277,0,3.0,0.032258,-0.806452,2.211763,4.523975,...,-0.014636,-0.028270,0.041054,-0.046555,0.0,-2.1,3.449001,7.261681,-3.812680,-3.812680
44,2003,137,1448,1190,1,-13.0,0.197957,8.570881,9.578159,-2.702395,...,0.010558,-0.026789,0.039999,0.053991,0.0,-0.8,0.139353,0.644374,-0.505021,-0.505021
45,2003,137,1190,1448,0,13.0,-0.197957,-8.570881,-9.578159,2.702395,...,-0.010558,0.026789,-0.039999,-0.053991,0.0,0.8,-0.139353,-0.644374,0.505021,0.505021
46,2003,137,1196,1358,1,-13.0,-0.003584,4.707288,8.253680,1.764893,...,0.034291,-0.028576,0.002508,-0.111571,-0.3,1.2,6.694923,4.732308,1.962615,1.962615
47,2003,137,1358,1196,0,13.0,0.003584,-4.707288,-8.253680,-1.764893,...,-0.034291,0.028576,-0.002508,0.111571,0.3,-1.2,-6.694923,-4.732308,-1.962615,-1.962615
48,2003,137,1246,1237,1,-15.0,0.312500,12.593750,7.515844,-9.783240,...,0.019215,-0.027670,0.045107,-0.069566,0.2,7.0,-0.394571,-8.458276,8.063705,8.063705
49,2003,137,1237,1246,0,15.0,-0.312500,-12.593750,-7.515844,9.783240,...,-0.019215,0.027670,-0.045107,0.069566,-0.2,-7.0,0.394571,8.458276,-8.063705,-8.063705
50,2003,137,1345,1261,1,1.0,-0.034562,-3.822581,-5.519656,0.708519,...,-0.067915,-0.005196,-0.025868,0.113316,-0.4,-12.7,-14.108324,4.415433,-18.523757,-18.523757
51,2003,137,1261,1345,0,-1.0,0.034562,3.822581,5.519656,-0.708519,...,0.067915,0.005196,0.025868,-0.113316,0.4,12.7,14.108324,-4.415433,18.523757,18.523757
52,2003,137,1393,1264,1,-11.0,0.034483,1.793103,3.667774,2.267601,...,0.014261,-0.006883,0.052423,-0.032148,0.1,-4.3,4.060955,11.076211,-7.015256,-7.015256
53,2003,137,1264,1393,0,11.0,-0.034483,-1.793103,-3.667774,-2.267601,...,-0.014261,0.006883,-0.052423,0.032148,-0.1,4.3,-4.060955,-11.076211,7.015256,7.015256
54,2003,137,1268,1423,1,-5.0,-0.121429,2.161905,1.138636,0.589107,...,-0.004496,0.019209,0.069869,0.020770,-0.4,-6.4,-0.026360,10.724021,-10.750381,-10.750381
55,2003,137,1423,1268,0,5.0,0.121429,-2.161905,-1.138636,-0.589107,...,0.004496,-0.019209,-0.069869,-0.020770,0.4,6.4,0.026360,-10.724021,10.750381,10.750381
56,2003,137,1329,1335,1,-5.0,-0.125160,-4.260536,-8.789241,-1.245719,...,-0.069025,0.011681,0.055668,0.040919,-0.7,-14.5,-20.005799,3.188036,-23.193835,-23.193835
57,2003,137,1335,1329,0,5.0,0.125160,4.260536,8.789241,1.245719,...,0.069025,-0.011681,-0.055668,-0.040919,0.7,14.5,20.005799,-3.188036,23.193835,23.193835
58,2003,137,1428,1332,1,1.0,0.047917,-1.516667,-1.360117,-1.612113,...,-0.005881,0.005213,-0.000382,0.048681,0.0,-2.2,0.241388,2.773150,-2.531761,-2.531761
59,2003,137,1332,1428,0,-1.0,-0.047917,1.516667,1.360117,1.612113,...,0.005881,-0.005213,0.000382,-0.048681,0.0,2.2,-0.241388,-2.773150,2.531761,2.531761

Saving matchup data

In [51]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent  # or Path("march-machine-learning-mania-2026")
output_dir = PROJECT_ROOT / "data" / "interim"

matchups.to_csv(output_dir / "men_train_matchups.csv", index=False)

Logistic Regression

In [52]:
from src.train_logreg import train_logreg
from src.train_xgb import train_xgb

model, logreg_feature_names = train_logreg()
xgb_model = train_xgb()

Baseline (6 feats) log loss: 0.5763305764083805
DROP  - efg_pct_diff           -> 0.5763711959019736
DROP  - tov_pct_diff           -> 0.5764323426168473
KEEP  + orb_pct_diff           -> 0.5761538002825893
KEEP  + ftr_diff               -> 0.5755634842761634
DROP  - last10_net_eff_diff    -> 0.5817279093161941
Final (8 feats) log loss: 0.5755634842761634
Final features: ['seed_diff', 'avg_margin_diff', 'off_eff_diff', 'def_eff_diff', 'net_eff_diff', 'win_pct_diff', 'orb_pct_diff', 'ftr_diff']
      target      pred  seed_diff  avg_margin_diff  off_eff_diff  \
2096       1  0.669373        0.0         8.512500     11.111882
2097       0  0.330627        0.0        -8.512500    -11.111882
2098       1  0.549169        0.0         0.136852      5.162797
2099       0  0.450831        0.0        -0.136852     -5.162797
2100       1  0.504676        0.0         2.022727      0.435941
2101       0  0.495324        0.0        -2.022727     -0.435941
2102       1  0.417377        0.0        -1.284946      7.690525
2103       0  0.582623        0.0         1.284946     -7.690525
2104       1  0.880302      -13.0         4.475444      5.682317
2105       0  0.119698       13.0        -4.475444     -5.682317
2106       1  0.684417       -7.0        -2.549632      0.042999
2107       0  0.315583        7.0         2.549632     -0.042999
2108       1  0.511228        1.0         0.438447      3.723336
2109       0  0.488772       -1.0        -0.438447     -3.723336
2110       1  0.574223       -5.0        -5.918750     -9.084910
2111       0  0.425777        5.0         5.918750      9.084910
2112       1  0.932694      -13.0        12.112299     14.019518
2113       0  0.067306       13.0       -12.112299    -14.019518
2114       1  0.972057      -15.0        21.529814     15.546598
2115       0  0.027943       15.0       -21.529814    -15.546598
2116       1  0.346350        3.0        -9.382353     -9.583202
2117       0  0.653650       -3.0         9.382353      9.583202
2118       1  0.725272       -9.0        -1.768382     -3.297102
2119       0  0.274728        9.0         1.768382      3.297102
2120       1  0.763243       -9.0        -0.524064     -7.400764
2121       0  0.236757        9.0         0.524064      7.400764
2122       1  0.274049        3.0        -5.109626     -3.800132
2123       0  0.725951       -3.0         5.109626      3.800132
2124       1  0.807766      -11.0         1.165179      2.415983
2125       0  0.192234       11.0        -1.165179     -2.415983
2126       1  0.369595        7.0         4.570533      6.021640
2127       0  0.630405       -7.0        -4.570533     -6.021640
2128       1  0.898314      -13.0         4.479779     -3.503316
2129       0  0.101686       13.0        -4.479779      3.503316
2130       1  0.857478      -11.0         4.051471     12.658037
2131       0  0.142522       11.0        -4.051471    -12.658037
2132       1  0.790364       -3.0        11.212121     13.404842
2133       0  0.209636        3.0       -11.212121    -13.404842
2134       1  0.575077       -5.0        -1.163102     -0.332616
2135       0  0.424923        5.0         1.163102      0.332616
2136       1  0.803796       -5.0         9.068182      6.574026
2137       0  0.196204        5.0        -9.068182     -6.574026
2138       1  0.286287        3.0        -4.833333      0.768995
2139       0  0.713713       -3.0         4.833333     -0.768995
2140       1  0.886983      -13.0         6.757576      5.647119
2141       0  0.113017       13.0        -6.757576     -5.647119
2142       1  0.964895      -15.0        17.392789      4.931933
2143       0  0.035105       15.0       -17.392789     -4.931933
2144       1  0.968586      -15.0        14.426411      8.482976
2145       0  0.031414       15.0       -14.426411     -8.482976
2146       1  0.927294      -11.0        11.632353      5.504559
2147       0  0.072706       11.0       -11.632353     -5.504559
2148       1  0.944570      -15.0        11.902462      4.516000
2149       0  0.055430       15.0       -11.902462     -4.516000
2150       1  0.239718        5.0        -5.693405     -9.558509
2151       0  0.760282       -5.0         5.693405      9.558509
2152       1  0.276131        9.0         2.277184      6.674647
2153       0  0.723869       -9.0        -2.277184     -6.674647
2154       1  0.344077        7.0         2.691105     -0.442895
2155       0  0.655923       -7.0        -2.691105      0.442895

      def_eff_diff  net_eff_diff  win_pct_diff  orb_pct_diff  ftr_diff
2096     -0.490792     11.602674      0.114583     -0.005120 -0.050851
2097      0.490792    -11.602674     -0.114583      0.005120  0.050851
2098      4.880874      0.281924     -0.055718     -0.002726 -0.089353
2099     -4.880874     -0.281924      0.055718      0.002726  0.089353
2100     -2.709515      3.145456      0.051136      0.111601  0.139932
2101      2.709515     -3.145456     -0.051136     -0.111601 -0.139932
2102      9.307638     -1.617113      0.016129     -0.139346  0.001173
2103     -9.307638      1.617113     -0.016129      0.139346 -0.001173
2104     -1.066570      6.748888      0.025078      0.091025  0.086504
2105      1.066570     -6.748888     -0.025078     -0.091025 -0.086504
2106      4.025232     -3.982233     -0.139706     -0.046629 -0.030915
2107     -4.025232      3.982233      0.139706      0.046629  0.030915
2108      3.406767      0.316569     -0.012311      0.082642 -0.041391
2109     -3.406767     -0.316569      0.012311     -0.082642  0.041391
2110     -1.231172     -7.853738     -0.145833      0.081824  0.045752
2111      1.231172      7.853738      0.145833     -0.081824 -0.045752
2112     -3.635711     17.655229      0.247772      0.072127 -0.012973
2113      3.635711    -17.655229     -0.247772     -0.072127  0.012973
2114    -13.875402     29.422000      0.328446      0.007845 -0.001628
2115     13.875402    -29.422000     -0.328446     -0.007845  0.001628
2116      2.866115    -12.449317     -0.319964      0.050454 -0.100293
2117     -2.866115     12.449317      0.319964     -0.050454  0.100293
2118      1.028532     -4.325635     -0.018382      0.058322  0.006535
2119     -1.028532      4.325635      0.018382     -0.058322 -0.006535
2120     -5.932824     -1.467941      0.038324      0.070356 -0.011978
2121      5.932824      1.467941     -0.038324     -0.070356  0.011978
2122      3.902492     -7.702624      0.011586      0.019385  0.053579
2123     -3.902492      7.702624     -0.011586     -0.019385 -0.053579
2124      0.618426      1.797557      0.062500      0.111483  0.070378
2125     -0.618426     -1.797557     -0.062500     -0.111483 -0.070378
2126     -0.693032      6.714672      0.134796      0.038578 -0.021359
2127      0.693032     -6.714672     -0.134796     -0.038578  0.021359
2128    -11.088934      7.585618      0.073529     -0.030380 -0.048012
2129     11.088934     -7.585618     -0.073529      0.030380  0.048012
2130      6.718282      5.939755     -0.045956      0.025739  0.002100
2131     -6.718282     -5.939755      0.045956     -0.025739 -0.002100
2132     -2.983623     16.388465      0.260606      0.033327 -0.075706
2133      2.983623    -16.388465     -0.260606     -0.033327  0.075706
2134      2.209340     -2.541955      0.068627     -0.002618  0.057568
2135     -2.209340      2.541955     -0.068627      0.002618 -0.057568
2136     -5.350121     11.924147      0.221591     -0.008694 -0.113329
2137      5.350121    -11.924147     -0.221591      0.008694  0.113329
2138      8.585236     -7.816241     -0.156863     -0.079978  0.039631
2139     -8.585236      7.816241      0.156863      0.079978 -0.039631
2140     -3.809899      9.457018      0.151515      0.015135  0.046072
2141      3.809899     -9.457018     -0.151515     -0.015135 -0.046072
2142    -18.334649     23.266582      0.336812      0.159887  0.018795
2143     18.334649    -23.266582     -0.336812     -0.159887 -0.018795
2144    -15.279377     23.762353      0.261089      0.071867 -0.088644
2145     15.279377    -23.762353     -0.261089     -0.071867  0.088644
2146    -11.644481     17.149040      0.193015      0.120513 -0.036974
2147     11.644481    -17.149040     -0.193015     -0.120513  0.036974
2148     -9.668083     14.184083      0.286932      0.088222 -0.064958
2149      9.668083    -14.184083     -0.286932     -0.088222  0.064958
2150     -0.702474     -8.856035     -0.100713     -0.007662  0.040914
2151      0.702474      8.856035      0.100713      0.007662 -0.040914
2152      2.962120      3.712527      0.095365      0.050683 -0.016644
2153     -2.962120     -3.712527     -0.095365     -0.050683  0.016644
2154     -5.674484      5.231589      0.109482     -0.086858 -0.058269
2155      5.674484     -5.231589     -0.109482      0.086858  0.058269
           feature  coefficient
0     orb_pct_diff     1.028587
1     net_eff_diff     0.033172
2  avg_margin_diff     0.022910
3     off_eff_diff     0.012947
4     def_eff_diff    -0.020225
5        seed_diff    -0.127956
6     win_pct_diff    -1.011673
7         ftr_diff    -1.825745
XGBoost Log Loss: 0.5911528188999162
                feature  importance
0             seed_diff    0.298428
1       avg_margin_diff    0.135888
2          net_eff_diff    0.119619
3              ftr_diff    0.066857
4   last10_net_eff_diff    0.061311
5          orb_pct_diff    0.055179
6          efg_pct_diff    0.054465
7          tov_pct_diff    0.053421
8          def_eff_diff    0.052564
9          off_eff_diff    0.051618
10         win_pct_diff    0.050652

Save Model

In [53]:
import joblib
from src import config
from src.train_logreg import save_logreg_artifacts

save_logreg_artifacts(model, logreg_feature_names)
joblib.dump(xgb_model, config.MODELS_DIR / "xgb_men.pkl")

['/Users/calebrh/model-madness/march-machine-learning-mania-2026/models/xgb_men.pkl']

In [54]:
# Stage 2 (2026): all pairs from SampleSubmissionStage2 → logreg + XGB probabilities
from src.predict_2026 import predict_stage2_matchups

pred_df = predict_stage2_matchups()
pred_df.head(10)

               ID  pred_logreg  pred_xgb
0  2026_1101_1102     0.717459  0.742751
1  2026_1101_1103     0.262383  0.264509
2  2026_1101_1104     0.172273  0.122964
3  2026_1101_1105     0.485343  0.527932
4  2026_1101_1106     0.451871  0.452736
5  2026_1101_1107     0.399779  0.553334
6  2026_1101_1108     0.608113  0.600956
7  2026_1101_1110     0.359784  0.238072
8  2026_1101_1111     0.357443  0.161052
9  2026_1101_1112     0.068527  0.037467

In [55]:
# 2026 Round of 64: resolve names via MTeamSpellings → TeamID, then logreg + XGB
from src.named_matchups import predict_first_round_2026_from_default_list

first_round_df = predict_first_round_2026_from_default_list()
# Columns: matchup_line, team_a_name, team_b_name, team_a_id, team_b_id, ID, pred_logreg, pred_xgb
first_round_df[
    ["team_a_name", "team_b_name", "pred_logreg", "pred_xgb"]
]

first_round_df

,matchup_line,team_a_id,team_b_id,team_a_name,team_b_name,ID,pred_logreg,pred_xgb
0,(8) Ohio State vs. (9) TCU | 12:15 p.m. | CBS,1326,1395,Ohio St,TCU,2026_1326_1395,0.536654,0.446975
1,(4) Nebraska vs. (13) Troy | 12:40 p.m. | truTV,1304,1407,Nebraska,Troy,2026_1304_1407,0.852710,0.881629
2,(6) Louisville vs. (11) South Florida | 1:30 p...,1257,1378,Louisville,South Florida,2026_1257_1378,0.719733,0.648487
3,(5) Wisconsin vs. (12) High Point | 1:50 p.m. ...,1458,1219,Wisconsin,High Point,2026_1458_1219,0.623948,0.598413
4,(1) Duke vs. (16) Siena | 2:50 p.m. | CBS,1181,1373,Duke,Siena,2026_1181_1373,0.951789,0.970277
5,(5) Vanderbilt vs. (12) McNeese | 3:15 p.m. | ...,1435,1270,Vanderbilt,McNeese St,2026_1435_1270,0.717784,0.701331
6,(3) Michigan State vs. (14) North Dakota State...,1277,1295,Michigan St,N Dakota St,2026_1277_1295,0.830651,0.857205
7,(4) Arkansas vs. (13) Hawai'i | 4:25 p.m. | TBS,1116,1218,Arkansas,Hawaii,2026_1116_1218,0.781833,0.841665
8,(6) North Carolina vs. (11) VCU | 6:50 p.m. | TNT,1314,1433,North Carolina,VCU,2026_1314_1433,0.646455,0.732906
9,(1) Michigan vs. Howard | 7:10 p.m. | CBS,1276,1224,Michigan,Howard,2026_1276_1224,0.932770,0.966370
10,(6) BYU vs. Texas | 7:25 p.m. | TBS,1140,1400,BYU,Texas,2026_1140_1400,0.723142,0.708478
11,(7) Saint Mary's vs. (10) Texas A&M | 7:35 p.m...,1388,1401,St Mary's CA,Texas A&M,2026_1388_1401,0.698128,0.662292
12,(3) Illinois vs. (14) Penn | 9:25 p.m. | TNT,1228,1335,Illinois,Penn,2026_1228_1335,0.933608,0.978019
13,(8) Georgia vs. (9) Saint Louis | 9:45 p.m. | CBS,1208,1387,Georgia,St Louis,2026_1208_1387,0.434987,0.369380
14,(3) Gonzaga vs. (14) Kennesaw State | 10 p.m. ...,1211,1244,Gonzaga,Kennesaw,2026_1211_1244,0.949206,0.968049
15,(2) Houston vs. (15) Idaho | 10:10 p.m. | truTV,1222,1225,Houston,Idaho,2026_1222_1225,0.942530,0.978297
16,(7) Kentucky vs. (10) Santa Clara | 12:15 p.m....,1246,1365,Kentucky,Santa Clara,2026_1246_1365,0.507619,0.420281
17,(5) Texas Tech vs. (12) Akron | 12:40 p.m. | t...,1403,1103,Texas Tech,Akron,2026_1403_1103,0.660711,0.660842
18,(1) Arizona vs. (16) Long Island University | ...,1112,1254,Arizona,LIU Brooklyn,2026_1112_1254,0.944545,0.986996
19,(3) Virginia vs. (14) Wright State | 1:50 p.m....,1438,1460,Virginia,Wright St,2026_1438_1460,0.893969,0.963019
20,(2) Iowa State vs. (15) Tennessee State | 2:50...,1235,1398,Iowa St,Tennessee St,2026_1235_1398,0.935840,0.982381
21,(4) Alabama vs. (13) Hofstra | 3:15 p.m. | truTV,1104,1220,Alabama,Hofstra,2026_1104_1220,0.723920,0.752770
22,(8) Villanova vs. (9) Utah State | 4:10 p.m. |...,1437,1429,Villanova,Utah St,2026_1437_1429,0.483686,0.547387
23,(6) Tennessee vs. (11) Miami (Ohio) | 4:25 p.m...,1397,1275,Tennessee,Miami OH,2026_1397_1275,0.764042,0.822998
24,(8) Clemson vs. (9) Iowa | 6:50 p.m. | TNT,1155,1234,Clemson,Iowa,2026_1155_1234,0.457453,0.490450
25,(5) St. John's vs. (12) UNI | 7:10 p.m. | CBS,1385,1320,St John's,Northern Iowa,2026_1385_1320,0.706674,0.599079
26,(7) UCLA vs. (10) UCF | 7:25 p.m. | TBS,1417,1416,UCLA,UCF,2026_1417_1416,0.669287,0.696298
27,(2) Purdue vs. (15) Queens | 7:35 p.m. | truTV,1345,1474,Purdue,Queens NC,2026_1345_1474,0.935765,0.984085
28,(1) Florida vs. (16) Prairie View A&M | 9:25 p...,1196,1341,Florida,Prairie View,2026_1196_1341,0.966175,0.982173
29,(4) Kansas vs. (13) Cal Baptist | 9:45 p.m. | CBS,1242,1465,Kansas,Cal Baptist,2026_1242_1465,0.778587,0.837907
30,(2) UConn vs. (15) Furman | 10 p.m. | TBS,1163,1202,Connecticut,Furman,2026_1163_1202,0.918738,0.983949
31,(7) Miami (Fla.) vs. (10) Missouri | 10:10 p.m...,1274,1281,Miami FL,Missouri,2026_1274_1281,0.727173,0.878443

In [56]:
# 2026: ad-hoc bracket-style block (seed + team lines) → predictions
from src.named_matchups import predict_seed_block_matchups_2026

seed_block_text = """
1
Duke

9
TCU

5
St John's

4
Kansas

11
South Florida

3
Michigan St

7
UCLA

2
UConn

1
Florida

8
Clemson

5
Vanderbilt

4
Nebraska

Preview
TBD

11
VCU

3
Illinois

7
Saint Mary's

2
Houston

1
Arizona

9
Utah State

12
High Point

4
Arkansas

6
BYU

3
Gonzaga

7
Miami

2
Purdue

1
Michigan

9
Saint Louis

5
Texas Tech

13
Hofstra

6
Tennessee

3
Virginia

10
Santa Clara

2
Iowa State
""".strip()

bracket_df = predict_seed_block_matchups_2026(seed_block_text)
bracket_df[["team_a_name", "team_b_name", "pred_logreg", "pred_xgb"]]

      team_a_name  team_b_name  pred_logreg  pred_xgb
0            Duke          TCU     0.884635  0.843633
1       St John's       Kansas     0.520296  0.611971
2   South Florida  Michigan St     0.240610  0.151247
3            UCLA  Connecticut     0.239616  0.137065
4         Florida      Clemson     0.824702  0.780222
5      Vanderbilt     Nebraska     0.415989  0.453623
6             VCU     Illinois     0.145213  0.097166
7    St Mary's CA      Houston     0.269236  0.336062
8         Arizona      Utah St     0.808775  0.885084
9      High Point     Arkansas     0.324345  0.312198
10            BYU      Gonzaga     0.223625  0.186306
11       Miami FL       Purdue     0.289893  0.359373
12       Michigan     St Louis     0.749877  0.701253
13     Texas Tech      Hofstra     0.749223  0.774212
14      Tennessee     Virginia     0.388861  0.335676
15    Santa Clara      Iowa St     0.186228  0.266643

XGBoost

In [57]:
# 2026: requested matchup set (keep prior seeds)
from src.named_matchups import predict_named_matchups_with_seeds

requested_matchups = """
(1) Duke vs. (5) St. John's
(1) Arizona vs. (4) Arkansas
(3) Gonzaga vs. (2) Purdue
(3) Michigan State vs. (2) UConn
(1) Florida vs. (4) Nebraska
(3) Illinois vs. (2) Houston
(6) Tennessee vs. (2) Iowa State
(1) Michigan vs. (5) Texas Tech
""".strip()

req_df = predict_named_matchups_with_seeds(requested_matchups)
req_df[["seed_a", "team_a_name", "seed_b", "team_b_name", "pred_logreg", "pred_xgb"]]

   seed_a  team_a_name  seed_b  team_b_name  pred_logreg  pred_xgb
0       1         Duke       5    St John's     0.781130  0.723589
1       1      Arizona       4     Arkansas     0.711102  0.792770
2       3      Gonzaga       2       Purdue     0.594270  0.581578
3       3  Michigan St       2  Connecticut     0.418932  0.333508
4       1      Florida       4     Nebraska     0.651925  0.531124
5       3     Illinois       2      Houston     0.458924  0.506501
6       6    Tennessee       2      Iowa St     0.277134  0.233269
7       1     Michigan       5   Texas Tech     0.730264  0.842998

In [ ]:
# Ad-hoc matchups (pred_* = P(team_a wins))
from src.named_matchups import predict_named_matchups

more_matchups = """
Nebraska vs. Houston
Michigan vs. Iowa State
Arizona vs. Gonzaga
Duke vs. Michigan St
""".strip()

more_df = predict_named_matchups(more_matchups)
more_df[["team_a_name", "team_b_name", "pred_logreg", "pred_xgb"]]